fertilizerShop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import LoginRedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', LoginRedirectView.as_view(), name='redirect-to-login'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^fertilizers/', include('fertilizers.urls', namespace='fertilizers')),
    url(r'^fertilizers/api/v1/', include('fertilizers.api.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fertilizers/api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token  # <-- Here
from django.conf.urls import include, url
from fertilizers.api import views


urlpatterns = [
    url(r'^get-api-token/', obtain_auth_token, name='api_token_auth'),
    url(r'^companies', views.CompanyList.as_view()),
    url(r'^company/(?P<company>[0-9a-zA-Z_-]+)', views.ProductList.as_view()),
]





urlpatterns = format_suffix_patterns(urlpatterns)

fertilizers/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.conf.urls.static import static


CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

urlpatterns = [
# /fertilizers/
    #url(r'', views.IndexView.as_view(), name='index'),
    #url(r'^$', cache_page(CACHE_TTL)(views.IndexViewCompany.as_view()), name='index'), #with redis cache
    url(r'^$', views.IndexViewCompany.as_view(), name='index'),  #without redis cache
    url(r'^Company/(?P<pk>[0-9]+)/$', views.DetailViewCompany.as_view(), name='Detail-company'),
    url(r'^Company/add/$', views.CreateViewCompany.as_view(), name='Add-company'),
    url(r'^Company/(?P<pk>[0-9]+)/$', views.UpdateViewCompany.as_view(), name='Update-company'),
    url(r'^Company/(?P<pk>[0-9]+)/delete/$', views.DeleteViewCompany.as_view(), name='Delete-company'),
    url(r'^Company/products/(?P<pk>[0-9]+)/$', views.DetailViewProduct.as_view(), name='Detail-product'),
    url(r'^Company/product/add/(?P<pk>[0-9]+)/$', views.CreateViewProduct.as_view(), name='Add-product'),
    url(r'^Company/product/(?P<pk>[0-9]+)/update/$', views.UpdateViewProduct.as_view(), name='Update-product'),
    url(r'^Company/product/(?P<pk>[0-9]+)/delete/$', views.DeleteViewProduct.as_view(), name='Delete-product'),
    url(r'^Company/product/(?P<pk>[0-9]+)/add2/$', views.CreateViewProductDetails.as_view(), name='Add-productdetails'),
              ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fertilizers/models.py
from django.db import models
import datetime
from django.utils import timezone

class Company(models.Model):
    Name = models.CharField(max_length=100)
    Amount_To_Pay = models.FloatField()

    def __str__(self):
        return self.Name

class Product(models.Model):
    company = models.ForeignKey(Company, null=True, on_delete=models.CASCADE)
    Date = models.DateField(default=datetime.date.today)
    Name = models.CharField(max_length=100)#, primary_key=True)

    def __str__(self):
        return self.Name

class ProductDetails(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    #Contact_Number = models.CharField(max_length=13)
    Date = models.DateField(default=datetime.date.today)
    #Name = models.CharField(max_length=100)#, primary_key=True)
    Opening_Balance = models.IntegerField()
    Receipt = models.IntegerField()
    Total = models.PositiveIntegerField(default=0,  editable=False)
    Sale = models.IntegerField()
    Closing_Balance = models.IntegerField(default=0,  editable=False)
    Invoice_Number = models.CharField(max_length=13)
    # Count = models.IntegerField()
    # Price_Per_Piece = models.FloatField()
    # Total_Amount = models.PositiveIntegerField(default=0,  editable=False)

    def __str__(self):
        return self.Invoice_Number

    def save(self, *args, **kwargs):
        #overriding save functionality of database
        # calculate sum before saving.
        #Reference :- https://docs.djangoproject.com/en/1.7/topics/db/models/#overriding-predefined-model-methods
        self.Total = self.Opening_Balance + self.Receipt
        self.Closing_Balance = self.Total - self.Sale
        #self.Total_Amount = self.Count * self.Price_Per_Piece
        super(ProductDetails, self).save(*args, **kwargs)  # Call the "real" save() method.

fertilizers/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Company, Product

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['Name', 'Amount_To_Pay']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['Name']

fertilizers/api/views.py
from fertilizers.models import Product, Company
from .serializers import ProductSerializer, CompanySerializer
from rest_framework.views import APIView
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework import status
from django.http import Http404
from django.core.urlresolvers import reverse_lazy
from rest_framework.permissions import IsAuthenticated  # <-- Here


class ProductList(APIView):
    permission_classes = (IsAuthenticated,)  # <-- And here
    def get_object(self, company):
        try:
            return Product.objects.filter(company__Name=company)
        except Product.DoesNotExist:
            raise Http404

    def get(self, request, company, format=None):    #
        #Below is the query set :- https://docs.djangoproject.com/en/2.1/topics/db/queries/
        #It will fetch the products belonging to particular company
        products = self.get_object(company)

        #This will tell you what objects you want to serialize
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

    def post(self, request, company):
        company = Company.objects.get(Name=company)
        data = request.data
        data["company"] = company.id
        serializer = ProductSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#Access companies list through this api  http://127.0.0.1:8000/companies/?format=api
class CompanyList(APIView):
    permission_classes = (IsAuthenticated,)  # <-- And here
    #model = Company
    def get(self, request):
        companies = Company.objects.all()

        #This will tell you what objects you want to serialize
        serializer = CompanySerializer(companies, many=True)
        return Response(serializer.data)

    def post(self, request):
        #serializer = CompanySerializer(data=request.data, files=request.FILES)
        serializer = CompanySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

fertilizers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, request, HttpResponseRedirect

from django.views import generic, View
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from .models import Product, Company, ProductDetails
from .tables import CompanyTable
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from .forms import UserForm, CompanyForm, ProductForm

class IndexViewCompany(generic.ListView):
    template_name = 'fertilizers/index.html'
    context_object_name = 'all_companies'

    def get_queryset(self):
        return Company.objects.all()


def company_list(request):
    table = CompanyTable(Company.objects.all())
    return render(request, 'fertilizers/index.html', {'table': table})

# class DetailViewCompany_copy(generic.DetailView):
#     model = Company
#
#     template_name = 'fertilizers/detail.html'
#
#     def dispatch(self, request, *args, **kwargs):
#         try:
#
#             self.company = Company.objects.get(id=self.kwargs['pk'])
#         except Exception as err:
#             print("Got error while fetching {}, {}".format(err, self.kwargs['pk']))
#         return super(DetailViewCompany, self).dispatch(request, *args, **kwargs)


class DetailViewCompany(generic.DetailView):
    model = Company

    template_name = 'fertilizers/AllProductsList.html'

    #The dispatch method takes in the request and ultimately returns the response
    #https://stackoverflow.com/questions/47808652/what-is-dispatch-used-for-in-django
    def dispatch(self, request, *args, **kwargs):
        try:
            print("Inside DetailViewCompany")
            self.company = Company.objects.get(id=self.kwargs['pk'])
        except Exception as err:
            print("Got error while fetching {}, {}".format(err, self.kwargs['pk']))
        return super(DetailViewCompany, self).dispatch(request, *args, **kwargs)


class DetailViewProduct(generic.DetailView):
    model = Product

    template_name = 'fertilizers/AllProductsList.html'
    print("You are inside function DetailViewProduct")
    def dispatch(self, request, *args, **kwargs):
        try:
            self.product = Product.objects.get(id=self.kwargs['pk'])
        except Exception as err:
            print("Got error while fetching {}, {}".format(err, self.kwargs['pk']))
        return super(DetailViewProduct, self).dispatch(request, *args, **kwargs)


class CreateViewCompany(CreateView):
    #By default createview will cal <model_name>_form.html template, so in this case it will call company_form.html template
    model = Company
    fields = ['Name', 'Amount_To_Pay']
    #form_class = Company
    success_url = reverse_lazy('fertilizers:index')

    def get_success_url(self):
        return reverse_lazy('fertilizers:index')

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(CreateViewCompany, self).post(request, *args, **kwargs)


class UpdateViewCompany(UpdateView):
    model = Company
    fields = ['Name', 'Amount_To_Pay']

    success_url = reverse_lazy('fertilizers:index')

class DeleteViewCompany(DeleteView):
    model = Company
    #fields = ['Name', 'Amount_To_Pay']
    success_url = reverse_lazy('fertilizers:index')


class CreateViewProduct(CreateView):
    #By default createview will cal <model_name>_form.html template, in this case, will call product_form html template
    model = Product
    fields = ['Date', 'Name']# 'Total_Amount']

    def get_success_url(self):
        return reverse_lazy('fertilizers:Detail-company', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        form.instance.company = Company.objects.get(id=self.kwargs.get('pk'))
        return super(CreateViewProduct, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(CreateViewProduct, self).post(request, *args, **kwargs)

class UpdateViewProduct(UpdateView):
    model = Product
    parent_model = Company
    fields = ['Date', 'Name']# 'Total_Amount']

    def get_success_url(self):
        obj = self.get_object()
        return reverse_lazy('fertilizers:Detail-company', kwargs={'pk': obj.company.id})


class DeleteViewProduct(DeleteView):
    model = Product

    def get_success_url(self):
        return reverse_lazy('fertilizers:Detail-company', kwargs={'pk': self.kwargs.get('pk')})


class CreateViewProductDetails(CreateView):
    model = ProductDetails
    fields = ['Date', 'Opening_Balance', 'Receipt', 'Sale', 'Invoice_Number']# 'Total_Amount']

    def get_success_url(self):
        return reverse_lazy('fertilizers:Detail-company', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        form.instance.product = Product.objects.get(id=self.kwargs.get('pk'))
        return super(CreateViewProductDetails, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(CreateViewProductDetails, self).post(request, *args, **kwargs)

# class UserFormView(View):
#     '''What is the blue print of the form'''
#     form_class = UserForm
#     template_name = 'music/registration_form.html'
#
#     #display blank form
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#
#     #Fill the form and post it. process form data
#     def post(self, request):
#         form = self.form_class(request.Post)
#
#         if form.is_valid():
#             #It creates an object from the form, and it doesn't save it to database.
#             user = form.save()
#
#             # cleaned (normalized) data
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user.username = 'Ramesh'
#             user.set_password(password)
#
#             #This will save user to database
#             user.save()
#
#             #returns User Objects if credentials are correct.
#             user = authenticate(username=username, password=password)
#
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('fertilizers:index')
#
#         return render(request, self.template_name, {'form': form})

fertilizers/templates/fertilizers/AllProductsList.html
{% extends 'fertilizers/base.html' %}
{% block title %}{{ company.Name }} contains product {% endblock %}
{% block product %}
    <a href="{% url 'fertilizers:Add-product'  company.id %}">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Product
    </a>
{% endblock %}


{% block body %}
<div id='sidebar'>
  <div class='toggle-btn' onclick="toggleSidebar()">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <ul id="list-of-products">
      {% for product in company.product_set.all %}
      <form action="{% url 'fertilizers:Detail-product' product.id %}" method="get" style="display:inline">
          {% csrf_token %}
          <!--<li><a id='{{ product.Name }}' onclick="openCity(event, '{{ product.Name }}', '{{ product.id }}')">{{ product.Name }}</a></li>-->
          <input type="hidden" name="product_id" value="product.id"/>
          <button type="submit" class="btn btn-default btn-sm">{{ product.Name }}</button>
      </form>
      {% endfor %}
  </ul>
</div>

<div id="main">
{% if company.product_set.all %}
    <div class="container-fluid" style="background-color:lightblue">
        <h3>Below are the list of products of company {{ company.Name }}</h3>
        <p>Type something in the input field to search the table for name, product name, seller name:</p>
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
        <br>
        <table class="table table-bordered">
            <thead>
                <th>Date</th>
                <!--<th>Name</th>-->
                <th>Opening Balance</th>
                <th>Receipt</th>
                <th>Total</th>
                <th>Sale</th>
                <th>Closing Balance</th>
                <th>Invoice Number</th>
            </thead>
            {% for productdetails in product.productdetails_set.all %}
            <tbody id="myTable">
            <tr>
                <td>{{ productdetails.Date }}</td>
                <!--<td>{{ product.Name }}</td>-->
                <td>{{ productdetails.Opening_Balance }}</td>
                <td>{{ productdetails.Receipt }}</td>
                <td>{{ productdetails.Total }}</td>
                <td>{{ productdetails.Sale }}</td>
                <td>{{ productdetails.Closing_Balance }}</td>
                <td>{{ productdetails.Invoice_Number }}</td>

                <td>
                    <!-- Update -->
                    <form action="{% url 'fertilizers:Update-product' product.id %}" method="" style="display:inline" onsubmit="return confirm('Sure you want to update');">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="product.id"/>
                        <button type="submit" class="btn btn-default btn-sm">Update</button>
                    </form>

                    <!-- Delete -->
                    <form action="{% url 'fertilizers:Delete-product' product.id %}" method="post" style="display:inline;" onsubmit="return confirm('Are you sure to delete');">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="product.id"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% else %}
    <h2>No products present for company {{ company.Name }}</h2>
{% endif %}
</div>

{% endblock %}

fertilizers/templates/fertilizers/AllProductsList_form.html
{% extends 'fertilizers/base.html' %}
{% block title %}Add New Entry to product{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 com-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="get" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'fertilizers/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="submit" class="btn btn-success" name="cancel" value="Cancel" formnovalidate>Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

fertilizers/templates/fertilizers/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Satisfy" type="text/css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'fertilizers/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'fertilizers/verticalTab.css' %}" />
    <script src="{% static 'fertilizers/addingRows.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% if user.is_authenticated %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'fertilizers:index' %}">Sugureshwara Fertilizers</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'fertilizers:index' %}">
                            <span class="glyphicon glyphicon-leaf" area-hidden="true"></span>&nbsp; Companies
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        {% block product %}
                        <a href="{% url 'fertilizers:Add-company' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Company
                        </a>
                        {% endblock %}
                    </li>

                    <li class="">
                        <a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>

                </ul>
            </div>

        </div>
    </nav>
    {% block body %}
    {% endblock %}
{% else %}
          <p>You are not logged in, please login with below link</p>
          <a href="{% url 'login' %}">login</a>
    {% endif %}
    </body>
</html>

fertilizers/templates/fertilizers/company_form.html
{% extends 'fertilizers/base.html' %}
{% block title %}Add New Company{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 com-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'fertilizers/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="submit" class="btn btn-success" name="cancel" value="Cancel" formnovalidate>Cancel</button>
                                    <!--<input type="submit" name="submit" value="Submit">-->
                                    <!--<input type="submit" name="cancel" value="Cancel" formnovalidate>-->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

fertilizers/templates/fertilizers/detail.html
{% extends 'fertilizers/base.html' %}
{% block title %}{{ company.Name }} contains product {% endblock %}
{% block product %}
    <a href="{% url 'fertilizers:Add-product'  company.id %}">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Product
    </a>
{% endblock %}
{% block body %}
{% if company.product_set.all %}
    <div class="container-fluid" style="background-color:lightblue">
        <h3>Below are the list of products of company {{ company.Name }}</h3>
        <p>Type something in the input field to search the table for name, product name, seller name:</p>
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
        <br>
        <table class="table table-bordered">
            <thead>
                <th>Date</th>
                <th>Name</th>
                <th>Opening Balance</th>
                <th>Receipt</th>
                <th>Total</th>
                <th>Sale</th>
                <th>Closing Balance</th>
                <th>Invoice Number</th>
            </thead>
            {% for product in company.product_set.all %}
            <tbody id="myTable">
            <tr>
                <td>{{ product.Date }}</td>
                <td>{{ product.Name }}</td>
                <td>{{ product.Opening_Balance }}</td>
                <td>{{ product.Receipt }}</td>
                <td>{{ product.Total }}</td>
                <td>{{ product.Sale }}</td>
                <td>{{ product.Closing_Balance }}</td>
                <td>{{ product.Invoice_Number }}</td>

                <td>
                    <!-- Update -->
                    <form action="{% url 'fertilizers:Update-product' product.id %}" method="" style="display:inline" onsubmit="return confirm('Sure you want to update');">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="product.id"/>
                        <button type="submit" class="btn btn-default btn-sm">Update</button>
                    </form>

                    <!-- Delete -->
                    <form action="{% url 'fertilizers:Delete-product' product.id %}" method="post" style="display:inline;" onsubmit="return confirm('Are you sure to delete');">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="product.id"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h2>No products present for company {{ company.Name }}</h2>
{% endif %}

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock %}

fertilizers/templates/fertilizers/form_template.html
{% for fields in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ fields.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ fields.label_tag }}</label>
        <div class="col-sm-10">{{ fields }}</div>
    </div>
{% endfor %}

fertilizers/templates/fertilizers/index.html
{% extends 'fertilizers/base.html' %}
{% block body %}
        {% if all_companies %}
            <h2>Here are all my company details:</h2>
            <div style="background-color:lightblue">
            <table class="table table-bordered">
                <thead>
                    <th>Company Name</th>
                    <th>Amount_To_Pay</th>
                    <th>Actions</th>
                </thead>
                {% for company in all_companies %}
                    <tr>
                        <td>{{ company.Name }}</td>
                        <td>{{ company.Amount_To_Pay }}</td>
                        <td>
                            <!-- Detail -->
                            <form action="{% url 'fertilizers:Detail-company' company.id %}" method="get" style="display:inline">
                                {% csrf_token %}
                                <input type="hidden" name="company_id" value="company.id"/>
                                <button type="submit" class="btn btn-default btn-sm">ProductList</button>
                            </form>

                            <!-- Update -->
                            <form action="{% url 'fertilizers:Update-company' company.id %}" method="" style="display:inline" onsubmit="return confirm('Sure you want to update');">
                                {% csrf_token %}
                                <input type="hidden" name="company_id" value="company.id"/>
                                <button type="submit" class="btn btn-default btn-sm">Update</button>
                            </form>

                            <!-- Delete -->
                            <form action="{% url 'fertilizers:Delete-company' company.id %}" method="post" style="display:inline;" onsubmit="return confirm('Are you sure to delete');">
                                {% csrf_token %}
                                <input type="hidden" name="company_id" value="company.id"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        {% else %}
            <h2>You don't have any company lists to display</h2>
        {% endif %}
{% endblock %}

fertilizers/templates/fertilizers/product_form.html
{% extends 'fertilizers/base.html' %}
{% block title %}Add New Product{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 com-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'fertilizers/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="submit" class="btn btn-success" name="cancel" value="Cancel" formnovalidate>Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}